### ISSUE TITLE
Preview Image and possibly text files

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#216] opened 2020-07-23 19:34 UTC
all of our visual testers complained that there was no preview button for the images and text files available.

This button would be located beside the download button and have the text "Preview" on the button.  The accessibility name would be identical to what we have for the "Download" button but have the word Preview instead of download and the file name.

Clicking that button would bring up a popup window with either a large view of the image or the text of the txt file which ideally they could copy to the clipboard if they so choose.  It would have one button close or escape will close the popup bringing you back to your resource file view where you left off.

I wouldn't expect all files to have a preview option only (Image and TXT) files.  
To be clear we don't expect to display videos even if we have them in our own collection.  That would be something post MVP.  Also if we can't display PDF's reliably we don't need to preview them.

**Comment by sinabahram** [comment] 2020-07-23 19:52
Marking this as an enhancement for future work.

**Comment by clapierre** [comment] 2020-07-24 19:25
@johnhbenetech are you able to return a different header from S3 buckets based on a query parameter like DL=0 vs. DL=1.

to download vs. to preview in the browser.

**Comment by johnhbenetech** [comment] 2020-07-24 21:00
@clapierre I don't think that is the best bang for our buck as I don't know a way to do that without layering unnecessary complexities.

I guess my thoughts are one of the following (i'm sure there's other stuff i'm not thinking of)

* Remove the content disposition entirely, and y'all would have to change the HTML to specify the download attribute for the link element on the download button. Then you have the control to handle the preview however you want.

* If we also think we might be interested in generating something like a thumbnail per resource, I can write a Lambda function to do that whenever something is added and add the preview as a separate file to a different directory. There are some cool libraries for auto-generating previews of even something like a 3D model.

**Comment by sinabahram** [comment] 2020-07-24 22:25
Happy to keep discussing this , but given the complexities involved, this will need to be one of the issues we visit in a future round of work.

**Comment by jkva** [comment] 2020-07-26 08:54
@clapierre @sinabahram  I've added the code to make this possible; however currently the S3 bucket has content-disposition set to allow for downloadable files, and this prevents files from being previewed as the browser tries to download them.
Other possibility I could think of is to pull it in async via a javascript `fetch` request and dynamically render, but that's more complex.

**Comment by sinabahram** [comment] 2020-07-26 21:17
That's easily fixed. @johnhbenetech  can remove that disposition header, but @jkva  can you ensure this does not then break the download buttons? If that's not possible, we'll need to move this to enhancement territory unless if there is another easy solution? Rendering anything or any new UI work/popups/modals/etc. are all not in scope, just to be clear.

**Comment by clapierre** [comment] 2020-07-27 15:49
@johnhbenetech has flipped the disposition header for the following two resources so you can test your code @jkva 

[Carbon](http://imgsdev.wpengine.com/btis_resource/6-carbon-library-lyna/)
and
[Eyeball](http://imgsdev.wpengine.com/btis_resource/eyeball-aph/)

Carbon contains Zip, JPG, STL, and TXT
Eyeball contains Zip, JPG, PDF, and TXT

Current behavior now for these two resources (now that John has removed that content-disposition header to be always download has been turned off)
When I click on Download we get:
Zip Files - Still are download
STL files - Still are downloaded
JPG files - Are now previewed in the same browser tab.
PDF files - Are now previewed in the same browser tab.
TXT files - Are now previewed in the same browser tab.

So as long as we can still get the Download to always download every file, then this seems to work.  

@sinabahram should we preview in the same browser window and the user can use the back button of the browser to get back to Imageshare, or should we bring up a new tab?

**Comment by jkva** [comment] 2020-07-27 19:06
@clapierre this basically just lets the browser decide what does with a connected resource.
If you want to fix this on the "type/format" level, then all disposition headers should remain as they are, and I would have to do the preview with a custom fetch request for the type+formats that are set to allow review. However it's added complexity at this point. @sinabahram

**Comment by sinabahram** [comment] 2020-07-27 20:45
My vote is to go back to how it was with preview scoped for future work.

**Comment by clapierre** [comment] 2020-07-27 20:55
I guess I am fine with this, but would like to know how much work it would be to add in this functionality so we can search for the funding to pay for this feature.  This was in the top three requested features.  I think the large image sizes for the thumbnails helps a lot which is why I am agreeing for now to push this to future work.  Now if this is something you can do in the next month that is also totally fine it doesn't have to happen by the end of this week.  We would just need to make sure we make the necessary changes to our S3 bucket accordingly.

@johnhbenetech Can you please revert back the content-disposition header for both "Eyeball" and "Carbon" so it has the downloadable attribute.

Thanks

**Comment by sinabahram** [comment] 2020-07-27 21:02
We'll see what can be done. If we can, via JS, determine the type and then change the behavior, we'll try to get that done this week, but if it requires any UI changes e.g. a preview box or anything like that, it's completely undoable this week because that hasn't been designed, tested, agreed to, marked up, etc. I hope that makes sense, and I feel it's beyond reasonable.

If we're going to try that, @johnhbenetech  should leave the disposition header off of the above resources so @jkva  can test different solutions. You can restore at the end of the week, depending on what is able to be done done.

**Comment by clapierre** [comment] 2020-07-27 21:07
Sounds great @sinabahram thanks for being flexible on this.  I can't tell you how excited we all are and my manager today was thrilled on how our user testing has gone and how responsive you and your team have been!
Agreed @johnhbenetech lets leave those two files as is for now and can adjust as needed at the end of the week.

**Comment by jkva** [comment] 2020-08-13 17:50
Hi @johnhbenetech what are the options regarding selectively making files downloadable? Is the content-disposition header an all-or-nothing or can that perhaps be controlled on a request-basis via parameter?

**Comment by johnhbenetech** [comment] 2020-08-13 22:59
@jkva I don't really know of a way to do it the "right" way easily. See my comment [here](https://github.com/benetech/Imageshare/issues/216#issuecomment-663732179). 

Currently, the header can be set at the object level or the whole "bucket" level. The two other approaches I can think of off the top of my head:

1. Hard option that would take more time: You integrate the AWS JS SDK to request a signed URI using the response-content-disposition parameter. In my experiments I can't find a way to do this through pure GET calls since it can't be done from an anonymous user

2. Hacky quick option: In the pre processing lambda script i just make two copies of each resource (or at least the resources of the file types we want to preview). There will be two files with different content dispositions and they would be differentiated at the top file tree eg:

/ImageshareResourceFiles/ vs. /ImageshareResourceFilesPreview/

**Comment by johnhbenetech** [comment] 2020-08-14 18:17
Ok nevermind @jkva and @clapierre I figured it out. good news, bad news...

Bad News: We will likely need to update all the resource URLs in the database, I haven't been following your import scripts but hopefully this isn't too hard :( I had to put Cloudfront in front of the s3 bucket (which I probably should have done anyway from the beginning, my bad). The URLs will now have a different domain (dqo7qtr60k265.cloudfront.net) but it's the same for all resources. So for example:

https://dqo7qtr60k265.cloudfront.net/ImageshareResourceFiles/Library+Lyna/6-Carbon.jpg

Good news: Now with this domain we can pass the ?response-content-disposition=attachment parameter optionally when you need it. So once we all agree, I can remove the disposition from the whole bucket and then you can change the download links to append that parameter. So for example:

https://dqo7qtr60k265.cloudfront.net/ImageshareResourceFiles/Library+Lyna/6-Carbon.jpg?response-content-disposition=attachment

**Comment by clapierre** [comment] 2020-08-14 19:44
@johnhbenetech , will the URL always be 
https://dqo7qtr60k265.cloudfront.net
for us?

right now our URL's to our images for preview / download look like


https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Thingiverse/T-Rex/The_T-Rex_Skull/images/The_T-Rex_Skull_featured.jpg


https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/OpenStax+Biology/carbon+cycle.zip
--
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/OpenStax+Biology/carbon+cycle.jpg
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/OpenStax+Biology/carbon+cycle-alt.txt
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/1-Hydrogen.zip
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/1-Hydrogen.jpg
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/1-Hydrogen.stl
https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/1-Hydrogen-alt.txt


So will it be a simple matter of search for 

imagesharemvp.s3.amazonaws.com
and replace with 
dqo7qtr60k265.cloudfront.net

Thats easy enough to do and then we would just delete all our resources and re-import everything.  The hardest part is the 150 resource limit (WPEngine time-out issue) so it will take me an hour or so to batch import 150 resources at a time due to the WPEngine limitation.  I have all the files already segmented like this its just matter of doing the manual uploading and then approving from draft to published for them all (also in batches of 150) 
which is how I have been doing it now.

But better to get this done now before we add even more resources the old way.
(or until we switch over to something other that WPEngine.)

**Comment by johnhbenetech** [comment] 2020-08-14 20:06
> So will it be a simple matter of search for
> 
> imagesharemvp.s3.amazonaws.com
> and replace with
> dqo7qtr60k265.cloudfront.net

Yep, should be - and then the code change is just adding the parameter when you do preview vs. download.

> The hardest part is the 150 resource limit (WPEngine time-out issue) so it will take me an hour or so to batch import 150
> resources at a time due to the WPEngine limitation.

Yeah hopefully we aren't running this migration all that often, but let me know if you want me to write a quick wrapper on the import to auto-batch it so at least you don't have to babysit it.

**Comment by clapierre** [comment] 2020-08-14 20:17
> but let me know if you want me to write a quick wrapper on the import to auto-batch it so at least you don't have to babysit it.

@johnhbenetech how would that work, this is in the Settings/Imageshare
https://imgsdev.wpengine.com/wp-admin/options-general.php?page=imageshare_settings

Resource file (JSON)  
Which I select a JSON file from my machine and then import and wait for 40+ seconds before it finishes and I do it with the next file.

**Comment by johnhbenetech** [comment] 2020-08-14 20:58
@clapierre anything is possible if you believe in yourself :)

Think headless click automation

**Comment by jkva** [comment] 2020-08-28 19:10
@clapierre @johnhbenetech is this something I can move ahead with on my side?

**Comment by sinabahram** [comment] 2020-08-28 19:23
Just to be clear, no preview modal or other popup window, two buttons of Download and Preview with the Preview button being disabled when not available, right @jkva ?

**Comment by jkva** [comment] 2020-08-28 19:25
@sinabahram correct. Effectively they would be a "Download" and "Preview" link with the only difference that the download link has the content disposition query parameter added.

**Comment by sinabahram** [comment] 2020-08-28 19:40
The only difficulty there is that links can't be disabled, so the preview link will simply not be output when it's not available, right?

**Comment by jkva** [comment] 2020-08-28 19:42
@sinabahram Yes. That will be achieved via a setting on the taxonomy level.

**Comment by johnhbenetech** [comment] 2020-08-28 20:27
@jkva technical side should be good to go. I'll leave it up to @clapierre on the product side

**Comment by sinabahram** [comment] 2020-08-28 21:21
As long as technical is good to go, @jkva  please proceed. Channeling Charles, he wants it yesterday *grin*! Please go for it.

**Comment by jkva** [comment] 2020-08-29 11:52
@johnhbenetech when testing locally on `https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/6-Carbon-alt.txt?response-content-disposition=attachment` I get:

```xml
<Error>
<Code>InvalidRequest</Code>
<Message>Request specific response headers cannot be used for anonymous GET requests.</Message>
<RequestId>E6CF72D3DDE90205</RequestId>
<HostId>byUhDmj1pOcxiB5if0Vh0KNf7FiZrjxISjiBw14EtUYPeH+eQHGFl9G80I2ojkhfAp00pWgBZc8=</HostId>
</Error>
```

A request to `https://imagesharemvp.s3.amazonaws.com/ImageshareResourceFiles/Library+Lyna/6-Carbon-alt.txt` works correctly.

**Comment by jkva** [comment] 2020-08-29 11:57
Amazon docs say:

> Note
You must sign the request, either using an Authorization header or a presigned URL, when using these parameters. They cannot be used with an unsigned (anonymous) request.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

**Comment by johnhbenetech** [comment] 2020-08-29 12:42
@jkva please see ![this comment](https://github.com/benetech/Imageshare/issues/216#issuecomment-674201447).

All the links now point to a cloud front domain instead of the s3 domain. The end of the URIs will be the same. So like two examples:

https://dqo7qtr60k265.cloudfront.net/ImageshareResourceFiles/Library+Lyna/6-Carbon.jpg


https://dqo7qtr60k265.cloudfront.net/ImageshareResourceFiles/Library+Lyna/6-Carbon.jpg?response-content-disposition=attachment

**Comment by jkva** [comment] 2020-08-29 12:45
@johnhbenetech right, so once everything is (re-)imported we are otherwise good to go, excellent. I'll push these changes.

**Comment by jkva** [comment] 2020-08-29 12:47
Addressed via https://github.com/benetech/Imageshare/commit/ac1e3ae654d1457c0543da856bbdd8bc7a18b7d1

**Comment by sinabahram** [comment] 2020-08-29 13:07
Sorry, but how can this be tested? I went here:
[http://imgsdev.wpengine.com/btis_resource/frog-dissection-with-tactile-2-5d-images-benetech/](http://imgsdev.wpengine.com/btis_resource/frog-dissection-with-tactile-2-5d-images-benetech/)

And I only see download links, no preview links. I did make sure to be in incognito this time :).

**Comment by sinabahram** [comment] 2020-08-29 13:09
Reading through the comments more carefully, it seems like we cannot close this issue until we do a re-import, so that's over to @clapierre, but let's leave this open until it can be confirmed working fully.

**Comment by jkva** [comment] 2020-08-29 13:13
Agreed. @sinabahram preview should be good now, I hadn't modified the taxonomy settings for the previewable file formats. Preview links are showing up for the dissected frog now.

**Comment by sinabahram** [comment] 2020-08-29 13:17
Nope, sorry, I went to that same link. All I see is "Download", no "Preview". I made sure to visit in in incognito, of course.

**Comment by jkva** [comment] 2020-08-29 13:18
@sinabahram under `Frog Dissection (print, color, labels) (JPG)` there are two links. I don't know what else to tell you :-/

**Comment by sinabahram** [comment] 2020-08-29 13:28
@jkva  I have now tested in Chrome incognito as well as Firefox. No, there aren't. I even did a view source, and searched for "prev". That char sequence does not appear anywhere in the markup, full stop. I'm happy to send you a screen shot ... as soon as I figure out how to do so without a printscreen key since I've mapped that to context menu. Could this be a WPEngine cache issue? It's not browser cache.

**Comment by sinabahram** [comment] 2020-08-29 13:29
![hopefully a screenshot showing a browser window with no preview links](https://user-images.githubusercontent.com/1811181/91637980-2f10e480-e9da-11ea-9aee-a1fd2f6eb265.png)

**Comment by jkva** [comment] 2020-08-29 13:33
How bizarre. I don't know what else it could be. I've opened that same page incognito in Firefox (as opposed to Chrome) and I'm seeing preview links.

**Comment by sinabahram** [comment] 2020-08-29 13:36
@johnhbenetech  are you seeing one of these two behaviors?

**Comment by johnhbenetech** [comment] 2020-08-29 13:50
@sinabahram @jkva I see both preview and download options on the frog dissection page

**Comment by sinabahram** [comment] 2020-08-29 13:56
Ok, it took forever, and @jkva  and I have no idea how my computer didn't see them for a bit (I blame WPEngine b/c that's statistically the most-likely :P). But, everything works now.

@clapierre  we need you to do a re-import to make the links actually behave as intended, but I'll go make a separate issue for that.

**Closed as completed by sinabahram** 2020-08-29 13:56 UTC
Labels: enhancement
