### ISSUE TITLE
Advance Search "--choose a ...-- with JAWS

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#232] opened 2020-07-28 20:59 UTC
This is not a huge deal but we noticed this and I am sure some users will find it annoying but when using JAWS and the user brings up the advance search you hear "dash dash choose a subject dash dash"
Same for --choose a type-- and --choose an accommodation--

would be great to remove the --'s so they won't have to always hear that if they have their pronunciation set to speak those dashes.

This is an enhancement and doesn't need to be completed by the end of the week.

**Comment by sinabahram** [comment] 2020-07-28 21:02
That's because of their punctuation/verbosity settings.

**Comment by jscholes** [comment] 2020-07-28 21:04
@clapierre The dashes ensure that the "Choose a ..." placeholder option doesn't become selected when using first-letter navigation/type-ahead.  I suppose a space could be used instead.

**Comment by clapierre** [comment] 2020-07-28 21:04
Right, I understand why its happening, but is this standard and we should keep it with -- choose xyz --  
If it is a standard I am happy to leave it. 
Space could work also I guess.  Totally your call Sina just want to see what your thoughts are on that.

**Comment by jscholes** [comment] 2020-07-28 21:07
My gut reaction is that if users have changed their pronunciation settings, they will often be aware of the consequences and be able to change it back.  However I know that' snot always true, and occasionally settings can end up being changed by accident.

With that in mind though, the dashes also serve the purpose of making it clear that the placeholder option isn't one of the valid suggestions.  So even if they are spoken, rather than it being annoying, I'd say they were fulfilling their purpose.

**Comment by sinabahram** [comment] 2020-07-28 22:27
Yup, agreed with all that. This is behaving as intended, as is Jaws, so I'm closing this issue.

**Closed as completed by sinabahram** 2020-07-28 22:27 UTC
Labels: enhancement, Accessibility
