### ISSUE TITLE
New File Group does not filter by parent resource

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#274] opened 2021-05-10 20:22 UTC
When creating a file group under a resource all files show up not just those associated with the parent resource.

**Comment by jkva** [comment] 2021-05-13 12:59
This was tricky without creating an entirely custom field type -- I've made changes in 1a55b3f015d963bbee54c4254b28c58334aa78c0 that only apply to a new file group being created. The available files update when you change the parent resource. 

@clapierre can you let me know if this is what you had in mind? Thanks :)

**Comment by clapierre** [comment] 2021-05-13 13:29
Hi @jkva This is getting better in the sense that I only can pick from ALL the resource files for this  parent resource but now there are three other issues.
1. we now always see ALL resources files for that resource even if we already have a resource file group with some of them in, we can select them again, (We should only see those resource files left in default), which then has the side effect of 
2. the same resource file is removed from the other file group.
3. the number of resource filess for this keeps going up when I go to the website and search for this resource.  (IE> the frog 2.5 D only should have 50 resource files, but now it says I can download 70 of them.  If I keep adding more resource groups  that number keeps increasing.

**Comment by jkva** [comment] 2021-05-13 15:03
> We should only see those resource files left in default

Ah, sorry - that requirement wasn't obvious to me. I'll add that filter.

> the number of resource filess for this keeps going up when I go to the website and search for this resource. (IE> the frog 2.5 D only should have 50 resource files, but now it says I can download 70 of them. If I keep adding more resource groups that number keeps increasing.

Sounds like a glitch. I'll have a look.

**Comment by jkva** [comment] 2021-05-19 09:52
> We should only see those resource files left in default

Addressed via 2c841aea328fce64e327a99a0b653b33ffe43909

> the number of resource files for this keeps going up when I go to the website and search for this resource. (IE> the frog 2.5 D only should have 50 resource files, but now it says I can download 70 of them. If I keep adding more resource groups that number keeps increasing.

That was a bug. Fixed in a35bc229e29b057230ecdb71c34e02996a405b59.

You might need to open and save the groups for that frog dissection resource again.

**Comment by clapierre** [comment] 2021-05-19 14:22
I assume @jkva  we are stuck with the fact that if you delete a file group after moving all the default files into this file group that when we delete it we can't automatically move the files back into the default group?
So we will need to be aware of this right?

Right now once I delete any file group the # of resource files now drops when viewing that resource by the # that was in the group deleted since those files don't belong to any file group associated with this resource.

If there is an easy fix to move them back into default I can create a new ticket for that otherwise we will have to live with this behavior.

**Comment by clapierre** [comment] 2021-05-19 14:29
Now nothing shows up when I select any parent resource, I get No Resources Found.

**Comment by jkva** [comment] 2021-05-19 14:59
> I assume @jkva we are stuck with the fact that if you delete a file group after moving all the default files into this file group that when we delete it we can't automatically move the files back into the default group?
> So we will need to be aware of this right?
> 
> Right now once I delete any file group the # of resource files now drops when viewing that resource by the # that was in the group deleted since those files don't belong to any file group associated with this resource.
> 
> If there is an easy fix to move them back into default I can create a new ticket for that otherwise we will have to live with this behavior.

Interesting edge case.

Effectively when a resource group is deleted, any files it owns are "freed". So what I hear you say in regards to desired functionality is:

1) a group gets deleted
2) IF it is the default group for a resource, the resources it contains become freed.
3) IF it is a non-default group for a resource, the resource it contains are moved to the default group for the resource.
3a) IF the resource has no default resource group, the resources become freed.

Do I understand this correctly?

> Now nothing shows up when I select any parent resource, I get No Resources Found.

Consistently everywhere or only in a particular scenario?

**Comment by clapierre** [comment] 2021-05-19 15:11
That all sounds good on deleting of groups.

> Now nothing shows up when I select any parent resource, I get No Resources Found.
> Consistently everywhere or only in a particular scenario?

Everywhere as far as I know,  I try to create a new Group, select a resource Parent and I get no files even thou it has files in its default group.

**Comment by jkva** [comment] 2021-05-19 15:14
I can't reproduce that locally nor on imgsdev, strange.

**Comment by clapierre** [comment] 2021-05-19 15:17
let me try on a different browser.

**Comment by sinabahram** [comment] 2021-05-19 15:18
Just to make sure nothing silly is going on. @clapierre  can you reproduce this in incognito to avoid any caching? Also a screen grab or screenshots may be helpful.

**Comment by clapierre** [comment] 2021-05-19 15:22
Ok, @jkva  it was a cache issue on Safari.  Working on other browsers and in private new window in Safari.

**Comment by sinabahram** [comment] 2021-05-19 15:27
Good to close?

**Comment by jkva** [comment] 2021-05-19 15:30
Tracking the group deletion edge case scenario in #276.

**Closed as completed** 2021-05-19 15:30 UTC
Labels: bug
