### ISSUE TITLE
PDF Images not always showing up

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#189] opened 2020-07-15 22:41 UTC
This seems intermittent, but could be browser related (not sure)
Safari at least currently works and shows the image of the PDF's as shown in this screenshot.

alt: safari Screenshot with pdf image
![Screen Shot 2020-07-15 at 3 36 54 PM](https://user-images.githubusercontent.com/7736749/87607111-7143c800-c6b1-11ea-9bce-d9d0f13563a4.png)

However both FF and Chrome on my Mac does not show the image for PDF's in the Resource file view as shown here:

alt: Firefox screenshot without pdf image
![Screen Shot 2020-07-15 at 3 35 53 PM](https://user-images.githubusercontent.com/7736749/87607125-786ad600-c6b1-11ea-9346-c29c8f1e7cac.png)

**Comment by sinabahram** [comment] 2020-07-15 22:45
@clapierre, can this reliably be reproduced in incognito? Since you've seen many versions of the site, your browser has all sorts of odd caching going on, but that won't exist for others, so I want to rule that out super-quick.

**Comment by clapierre** [comment] 2020-07-15 22:52
@sinabahram this was with one of our testers we had today who has never been on our website so no chance of cache issues

**Comment by clapierre** [comment] 2020-07-15 23:28
BTW, she was running Chrome on a PC.

**Comment by jkva** [comment] 2020-07-17 18:47
Implemented via ef0bc42365b96cba7c8d38fc3297a5df64743846

You can now configure a file format to use the resource uri as a thumbnail source.

**Comment by sinabahram** [comment] 2020-07-17 19:36
@jkva  seems to be some misunderstanding here. We don't need the preview image at all displayed so can we back out this commit, please? @clapierre  is simply pointing out that on both the search results page as well as on the files view, the PDF icons (the icon from marketing) is not showing up, even though it is for 2D, image, text, etc. .... that's the actual bug needing to be fixed here.

**Comment by jkva** [comment] 2020-07-17 19:49
Sorted via eab573b979d5a7f2427e403c79857efef133b3d5. The original commit is still relevant because I've added the logic for types and formats to contain thumbnail metadata, instead of string type comparison. So I'm overall happier with this solution.

**Comment by clapierre** [comment] 2020-07-17 20:26
@jkva Yes it now shows the PDF Icon in the file Resources view.
However it doesn't show up in the Search Results view for this resource.

I would expect to see the PDF icon along with the image icon, txt icon and 2D icon.

IE:
![Screen Shot 2020-07-17 at 1 24 40 PM](https://user-images.githubusercontent.com/7736749/87828123-20f37400-c831-11ea-9eed-1e31edd6d6a4.png)

**Comment by jkva** [comment] 2020-07-23 19:15
Resolved via 55f1f311273ea1dc676a57f232a712bbe7aa04d5

**Closed as completed by jkva** 2020-07-23 19:15 UTC
