### ISSUE TITLE
Blank Search results from Resources "File Groups" Search

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#267] opened 2021-03-29 17:25 UTC
In the Resources "File Groups" section there is a "Search..." field and below that shows all the File Groups in a list.
Currently when you type in any character into this search field you always get "No Matches Found"

I had to scroll down to the "F's in order to find "Frog Dissection Braille Labels" in order to add that to the Frog Dissection resource.

**Comment by jkva** [comment] 2021-03-29 20:53
What a strange problem - I'm unable to reproduce it locally. @johnhbenetech can you provide me with a copy of the imgsdev instance so I can try to reproduce?

**Comment by johnhbenetech** [comment] 2021-03-29 21:16
@jkva @clapierre I can't reproduce on imgsdev either.

@clapierre which browser are you using? can you try a different browser as well just for sanity's sake

**Comment by johnhbenetech** [comment] 2021-03-29 21:43
@jkva ill send link on slack

**Comment by johnhbenetech** [comment] 2021-03-30 16:18
@jkva I have limited knowledge of ACF and even less knowledge of our specific implementation, but I though I would point out in case it's the root cause:

For the Resource field, the File Group subfield is type 'Relationship', when I look at other fields (let's say the File Group field itself) the subfield type is 'Relationship (Imageshare)' - so not sure if that could be an issue

**Comment by jkva** [comment] 2021-03-30 17:14
@johnhbenetech I tried to see if that was the issue since I can't reproduce it on the dev instance -- it used to be a custom `Imageshare` relationship field (which supports status filtering) but it doesn't seem to make a difference. Thanks for the export - that should help.

**Comment by jkva** [comment] 2021-04-05 19:08
Fixed in 7d05ee0.

**Closed as completed by jkva** 2021-04-05 19:08 UTC
Labels: bug
