### ISSUE TITLE
Solution for the Image Icon "Type" Legend.

### ISSUE THREAD

**Issue by clapierre** [benetech/ImageShare#192] opened 2020-07-15 23:40 UTC
During our testing today the suggestion of a legend of all the icons came up.
It was suggested that In the advance Search there is the "Type" dropdown.

Would we be able to add the icon followed by the Type's text inside that dropdown?
We wouldn't need the alt text for the icon here since the text of the image is right beside the image so it would be alt="" for each of the images in the dropdown list of Types.

**Comment by jkva** [comment] 2020-07-17 18:05
This is possible but requires a custom dropdown box with the ARIA etc that it needs. Just checking if that's what you want.

**Comment by sinabahram** [comment] 2020-07-17 18:42
If we go this way, we need to follow the ARIA 1.2 pattern. This is non-optional and will require a fair bit of testing on our side to make sure it works perfectly on Firefox, Chrome, Safari, and on mobile as well.

I hesitate to introduce such a change this late in the process, but if this is the ask, there is a known accessible solution by way of the aria 1.2 pattern.

**Comment by clapierre** [comment] 2020-07-17 20:28
Good chat with @sinabahram on this.
We still think it's a good idea, but this is lower priority than the other Issues currently in our system.

**Comment by jkva** [comment] 2020-08-14 12:03
@clapierre I've placed an early version on the development site. Could you have a look and let me know if this is the type of functionality you had in mind?

**Comment by jkva** [comment] 2020-08-14 12:18
Styling is tricky because we're dealing with browser default styles and a custom control.

**Comment by clapierre** [comment] 2020-08-14 12:25
Hi @jkva looking good two points.
1. Once you pick your selection can the Icon along with text also appear in the edit box area?  Currently we only see the text once you select a choice.
2. There is no way to unselect your choice like you you use to be able to do
ie --choose a type-- is not offered as a dropdown choice.

**Comment by jkva** [comment] 2020-08-14 12:58
@clapierre I've done so now, have a look. There's not much room for the image, alternatively we could give all the other select elements a bit of margin to account for that.

**Comment by clapierre** [comment] 2020-08-14 14:53
Yes this looks good.
I noticed 3 other small things.
1. Can we make the dropdown larger not everything is shown like it is with the other dropdown.
IE:
alt: can't see all entries in dropdown list
![Screen Shot 2020-08-14 at 7 45 26 AM](https://user-images.githubusercontent.com/7736749/90261881-6e4c0c80-de02-11ea-9808-3b69eb8937f1.png)

Vs. 
Alt: all a11y accommodations which is a large list shows the entire dropdown
![Screen Shot 2020-08-14 at 7 46 49 AM](https://user-images.githubusercontent.com/7736749/90261967-8754bd80-de02-11ea-93a1-1b1301b6fb99.png)


2. Dropdown arrow looks different (not blue up/down arrow)
![Screen Shot 2020-08-14 at 7 45 41 AM](https://user-images.githubusercontent.com/7736749/90262126-bc611000-de02-11ea-8b50-9f3ee96bb5fa.png)

3. Not sure if you can address this but when open the accessibility accommodation and mouse click on an item that item is selected and the dropdown goes away, but this doesn't happen for Type anymore, the item you click on does get selected but you must click outside the dropdown to make it go away.  Keyboard selecting of an item does select and close the dropdown correctly.  (Same behavior on all browsers I tested safari/firefox/chrome)

**Comment by jkva** [comment] 2020-08-23 12:55
@clapierre I've addressed #1 and #3; when #2 is the case this is because of custom controls versus browser default controls. The only way to sort that is to switch all the dropdown controls to custom controls, which seems overkill to me (and violates rule #1 of ARIA)

**Comment by sinabahram** [comment] 2020-08-23 19:17
@jscholes  may I have you please report back on any accessibility issues with the implementation of this type combobox before we fully close out this issue?

you can see it on the [Imageshare Dev Homepage](http://imgsdev.wpengine.com/) by expanding advanced search:

Thanks

**Comment by jscholes** [comment] 2020-08-23 19:23
@jkva Semantically, this is implemented as a menu button that invokes a list box, not a select-only combo box.  As a result it's completely inconsistent with the selects to either side of it.

**Comment by jkva** [comment] 2020-08-23 19:24
@jscholes so much for using the APG patterns... I literally took this from their example implementation.

**Comment by jkva** [comment] 2020-08-23 19:25
I _did_ use their listbox pattern; I'll switch implementation to their combobox pattern and will see if that improves things.

**Comment by jscholes** [comment] 2020-08-23 19:50
@jkva In effect what we want here is a read-only combo box, but support for those is pretty terrible right now.  E.g. there is an implementation with no input element discussed at https://www.24a11y.com/2019/select-your-poison-part-2/.  When I test that one in Firefox with NVDA, I don't hear the currently selected option spoken automatically, and selection doesn't really work within the list box either.  That could be because of the implementation though.

If we can't create a read-only combo box reliably, then we may need to have one which supports autocomplete.  At that point, we really should switch the other selects to use the same pattern, or the same inconsistency issue will occur.

**Comment by jkva** [comment] 2020-08-23 20:00
For these reasons alone I'd rather just use non-custom selects everywhere and sacrifice the fancy image-in-option for operability and consistency.

**Comment by sinabahram** [comment] 2020-08-23 20:12
May i recommend this, please?

[Select only Combobox from ARIA 1.2](http://raw.githack.com/w3c/aria-practices/master/examples/combobox/combobox-select-only.html)

**Comment by sinabahram** [comment] 2020-08-23 20:13
Oh, I should say the above says ARIA 1.2, but really it's from the master branch of APG that will align against 1.2.

**Comment by jkva** [comment] 2020-08-23 20:14
@sinabahram that link is 404.
edit: never mind, found it.

**Comment by jkva** [comment] 2020-08-23 20:16
Doesn't look too different. I can probably implement that.

**Comment by sinabahram** [comment] 2020-08-23 20:21
Gah, stupid copy/paste. Now fixed, and sorry about that @jkva

**Comment by jscholes** [comment] 2020-08-23 20:34
@sinabahram That is the sort of pattern I was referencing above, but with Firefox and NVDA:

* the currently selected option isn't communicated when I tab to the combo box; and
* NVDA reports each item as being not selected.

In Chrome, only the second of the above bullet points applies.

**Comment by jscholes** [comment] 2020-08-23 20:38
I think the selection-related behaviour is because of their code; `aria-selected` is only updated when I confirm my choice e.g. via Enter, and not as I move through the options with the Arrow keys.  So we could probably fix that, but the lack of selected option indication in Firefox is problematic.

I should also point out that if we use a custom dropdown for one option of three, the other two will be inconsistent on MacOS where the menu button-style pattern is the norm.  So whatever we decide on, let's use it everywhere.

**Comment by sinabahram** [comment] 2020-08-23 21:44
@jscholes  has the combobox not reporting its value issue been reported to Mozilla? I'm guessing that's a Firefox bug. The not selected can be fixed by us, which is great, and so that only leaves consistency, for which we can do as you say and replace the others with this pattern.

There's only one functional choice here, which is to use this pattern, right? Otherwise, we cannot achieve the icons within a native select, which is why we bothered with any of this in the first place. So, either we undo this and we have to lose that functionality or we do as above and hope the Firefox issue gets addressed, as it isn't our problem.

Let me know if I'm missing something.

**Comment by jscholes** [comment] 2020-08-24 16:05
> has the combobox not reporting its value issue been reported to Mozilla?

Not by me.  Would need to investigate whether someone else has raised it.

> There's only one functional choice here, which is to use this pattern, right?

As I see it, we have three pattern choices:

1. this one;
2. an editable/autocomplete combo box; and 
3. the menu button/list box one.

I'd say `#2` is out, because an editable context just isn't appropriate here.  For `#1`, I agree that it's Firefox's responsibility to fix, but I also know we haven't done a huge amount of testing e.g. on mobile, Mac, etc.

So my question is, if we're looking for consistency and guaranteed accessibility, should we go for pattern `#3`, even though it's the least native-feeling on Windows?  We know that it works pretty much everywhere.

**Comment by sinabahram** [comment] 2020-08-24 17:09
doesn't that mean we lose first-letter navigation and type-ahead? No, I'm not ok with that if so.

**Comment by jscholes** [comment] 2020-08-24 17:17
> doesn't that mean we lose first-letter navigation and type-ahead?

No, not if the list box is implemented correctly.  It can have Home, End, first letter nav and multiletter typeahead.  But the combo box also uses a list box, so the concerns apply regardless of which pattern is used.

**Comment by sinabahram** [comment] 2020-08-24 17:22
It just feels so weird in Windows, but I'm fine with it. You're suggesting aria-haspopup on a button then? From that point, arrow keys and just whack enter when done? That will make iOS VO and Mac OS X VO happy of course, and NVDA/Jaws both support that pattern well. It's also less work for @jkva . I'm fine to proceed.

**Comment by jscholes** [comment] 2020-08-24 17:26
@jkva has already implemented this pattern based on APG advice, so I will need to test it before we apply it to each dropdown.  I can look at that in a couple of hours.

Agreed about it feeling weird in Windows, but a combo box would feel weird on the Mac and iPhone.  This is the problem with custom combo boxes; there is no way to precisely recreate a native-feeling control by following a single pattern.

**Comment by sinabahram** [comment] 2020-08-24 17:31
Well, then we may have some issues because the implemented version most-certainly does not support first-letter navigation. This is critical, not for type, as that's only 7 items, but some of the other ones have dozens of choices.

**Comment by jscholes** [comment] 2020-08-24 17:38
@jkva Can you implement first-letter navigation and typeahead into the list box?  E.g., in "Type", I should be able to type "I" for "Image", but also "im", "ima", etc. if I type fast enough.

@sinabahram I will fully test it from other perspectives this afternoon.

**Comment by jscholes** [comment] 2020-08-24 21:39
@jkva In addition to the missing support for first-letter nav/type-ahead:

1. When the list box is expanded, focus is placed directly on it rather than the selected (or first) item.  It's worth noting that the WAI-ARIA Authoring Practices document says the following:

    > When a single-select listbox receives focus: ... If none of the options are selected before the listbox receives focus, the first option receives focus. Optionally, the first option may be automatically selected. If an option is selected before the listbox receives focus, focus is set on the selected option.

    But, despite that, their Collapsible Dropdown Listbox Example doesn't implement this behaviour.

2. The triggering button uses `aria-labelledby`, so there is no pause in screen reader speech between the name of the dropdown ("Type") and the text of the currently selected option.  We could fix this either by:
    1. adding a colon after dropdown label text (for all dropdowns); or
    2. using `aria-label` instead.
3. Because of the `<img>`, NVDA at least is picking up a space before the option text.  This isn't really an issue, unless it interferes with first-letter nav and/or type-ahead.

I think that's all I can spot.

**Comment by jkva** [comment] 2020-08-27 18:12
@jscholes So addressing these 3 issues plus first-letter navigation and typeahead would make this suitable to use?

**Comment by jscholes** [comment] 2020-08-27 18:14
@jkva Yup.  Not ideal, and it's a bit ridiculous that `<option>` doesn't support anything but text in 2020.  But it will work.

**Comment by jkva** [comment] 2020-08-28 18:57
@jscholes I've made a number of changes addressing your points - can you check and let me know? Thanks 👍

**Comment by jscholes** [comment] 2020-08-28 19:18
@jkva The colon after "Type" is visually hidden, but when used in the accessible name of the triggering button that means there's a space between "Type" and the colon.  This imposes a longer pause than expected with some speech engines.  Do we really need to hide the colon?  If so, can we use `aria-label` instead on the button, with the pattern `"<label>: <current choice>"`?

Other than that, it all seems to be working well.  What is the typeahead timeout set to?  It seems a little long, but it's difficult to test because all of the options in this list box begin with a different letter.

**Comment by jkva** [comment] 2020-08-28 19:22
> Do we really need to hide the colon?

Not necessarily, if the goal is to make all these select controls a custom element they can also all have the colon as part of their label. So that would fix it.

> What is the typeahead timeout set to?

500ms.

**Comment by sinabahram** [comment] 2020-08-28 19:25
Let's do 300ms at most, please. Thanks much!

**Comment by jkva** [comment] 2020-08-28 19:30
> Let's do 300ms at most, please. Thanks much!

Done.

**Comment by jscholes** [comment] 2020-08-28 19:43
Cool.  Let's show the colon and roll it out for the others.

**Comment by sinabahram** [comment] 2020-08-28 19:43
Very cool. I like that performance. @jscholes  you good with this?

**Comment by jscholes** [comment] 2020-08-28 19:44
@sinabahram  Sure.

**Comment by jkva** [comment] 2020-08-28 20:53
@jscholes I've converted the other selects. Give it a whirl if you like.

**Comment by jscholes** [comment] 2020-08-28 21:17
@jkva Works great!  I notice that the "Accommodation" list isn't sorted alphabetically; is that an intentional choice to have captions, audio descriptions, etc. near each other?

**Comment by jkva** [comment] 2020-08-29 12:48
@jscholes yes, they go by category.

**Comment by jkva** [comment] 2020-08-29 12:48
Implemented via 03e2840316a1a7c8f030cdca32dfefa3df1c8fee

**Comment by sinabahram** [comment] 2020-08-29 12:56
These are now completely inaccessible with NVDA and Chrome. Haven't checked with other screen readers yet. Can't even activate them with the keyboard. I think something went wrong :).

**Comment by sinabahram** [comment] 2020-08-29 12:58
Update, maybe a caching issue? Getting different results in incognito. Still investigating.

**Comment by jkva** [comment] 2020-08-29 13:02
@sinabahram I bumped the theme version with the update, that should bust the cache, but it works fine for me in chrome. NVDA support works well too.

**Comment by sinabahram** [comment] 2020-08-29 13:03
Ok, *huge sigh of relief*, I've confirmed that they work with NVDA on Chrome and Firefox, but it is absolutely critical that you use incognito if you've been to the site before. The cached version is completely broken/inaccessible. I'm guessing some JS asset isn't getting updated. If we can clear the WPEngine cache @johnhbenetech , that would be great. Otherwise, @jscholes  heads up to use incognito. I'll re-close this issue.

**Closed as completed by sinabahram** 2020-08-29 13:03 UTC
Labels: enhancement

**Comment by johnhbenetech** [comment] 2020-08-29 13:08
Cache wiped!
